### ISSUE TITLE
Recommended Storage For MySQL and Postgres

### ISSUE THREAD

**Issue by crc-sstubbs** [dylanhart/ulid-rs#51]
Hi,

Firstly thanks for this amazing crate. I intend to use this for primary keys in a MySQL and potentially Postgres database. How would you suggest I store these? Could I use binary or just use the 26-character representation? I have looked at this https://github.com/ulid/spec/issues/25 but not sure how it relates to this implementation. Another option is converting them to UUIDs and storing them as native uuid types in the databases but not sure if this would retain the sorting information.

**Comment by dylanhart** [comment]
* A binary format would be preferred since there is no ambiguity or duplication (like uppercase vs lowercase). 
* The binary format is smaller.
* Converting to uuid and back is lossless, but the derived uuid will not have sensible version information.
* The best way to compare is to test and measure performance.

**Comment by mqudsi** [comment]
Note that MySQL has issues creating foreign keys against blob primary keys or keys of variable length. On Postgres, you can store ulids as uuid type.
